Add license
music-encoding/sample-encodings pull request #73
Opened 2022-10-04 09:29 UTC by rettinghaus

This PR adds a license as decided during MEI Board meeting.

2022-10-04 19:35 UTC, musicEnfanthen requested changes

2022-10-04 19:35 UTC, musicEnfanthen commented on README.md
> +The MEI Sample Encodings contain a wide range of MEI-encoded music files. The intent is to demonstrate the use of MEI in real-world contexts. The current MEI Release is 4.0.1. Samples from previous r
```suggestion
The MEI Sample Encodings contain a wide range of MEI-encoded music files. The intent is to demonstrate the use of MEI in real-world contexts. The current MEI Release is 4.0.1. Samples from previous releases may be found in the `MEI_3.0` and `legacy` directories.
```

2022-10-04 19:35 UTC, musicEnfanthen commented on README.md
> +If you are not comfortable with this process but would still like to contribute, please get in touch with the MEI Technical Team.
```suggestion
If you are not comfortable with this process but would still like to contribute, please get in touch with the [MEI Technical Team](https://music-encoding.org/community/technical-team.html).
```

2022-10-04 20:23 UTC, rettinghaus commented
@musicEnfanthen thank you for the review.

2022-10-04 21:20 UTC, musicEnfanthen approved these changes

2022-10-04 21:20 UTC, merged

2022-10-04 22:48 UTC, craigsapp commented
I will point out that the file https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Scarlatti_Sonata_in_C_major.mei

is a derivative electronic edition of this file https://github.com/craigsapp/scarlatti-keyboard-sonatas/blob/master/kern/L001K514.krn

which has a more restrictive license: 
https://github.com/craigsapp/scarlatti-keyboard-sonatas/blob/master/LICENSE.txt
https://creativecommons.org/licenses/by-nc-sa/4.0

2022-10-05 06:06 UTC, th-we commented
Other files where I sense licensing problems because they are not public domain:

* [Ives_TheCage.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Ives_TheCage.mei) († 1954)
* [Hopkins_GatherRoundTheChristmasTree.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Hopkins_GatherRoundTheChristmasTree.mei) ([CC-BY](https://imslp.org/wiki/Gather_Round_the_Christmas_Tree_(Hopkins_Jr.%2C_John_Henry)))
* [McFerrin_Don't_worry.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/McFerrin_Don't_worry.mei) (* 1950)

There are some arrangements that might not be kosher, either, e.g. the ones by Michel Rondeau, which seem to be CC-BY:

* [Handel_Messias.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Handel_Messias.mei)
* [Beethoven_Hymn_to_joy.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Beethoven_Hymn_to_joy.mei)
* [Telemann_Concert.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Telemann_Concert.mei)
* [Schutz_Jubilate_Deo.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Schutz_Jubilate_Deo.mei)
* [Hummel_Concerto_for_trumpet.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Hummel_Concerto_for_trumpet.mei)
* [Praetorius_PuerNobisNascitur.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Praetorius_PuerNobisNascitur.mei)
* [Lully_LaDescenteDeMars.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Lully_LaDescenteDeMars.mei)
* [Bach_BrandenburgConcert_No.4_II.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Bach_BrandenburgConcert_No.4_II.mei)
* [Telemann_Suite.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Telemann_Suite.mei)
* [Handel_Arie.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Handel_Arie.mei)
* [Gluck_CheFaroSenzaEuridice.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Gluck_CheFaroSenzaEuridice.mei)
* [Berlioz_Symphony_op25.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Berlioz_Symphony_op25.mei)
* [Czerny_StringQuartet_d.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Czerny_StringQuartet_d.mei)
* [Bach_BrandenburgConcert_No.4_I.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Bach_BrandenburgConcert_No.4_I.mei)
* [Kirnberger_FugeInEFlatMajor.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Kirnberger_FugeInEFlatMajor.mei)
* [Bach-J-C_Fughette_No2.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Bach-J-C_Fughette_No2.mei)
* [Bach-J-C_Fughette_Gmaj.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Bach-J-C_Fughette_Gmaj.mei)
* [Hopkins_GatherRoundTheChristmasTree.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Hopkins_GatherRoundTheChristmasTree.mei)

But I'm not sure if the term "arranger" was used technically correct or if he is really acting as a typesetter rather than an arranger. [Saint-Saens_LeCarnevalDesAnimaux.mei](https://github.com/music-encoding/sample-encodings/blob/main/MEI_4.0/Music/Complete_examples/Saint-Saens_LeCarnevalDesAnimaux.mei) is however a true arrangement by Martin Packham (* 1978, no license specified).